AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy a single EC2 instance with minimal configuration

Resources:

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-04681a1dbd79675a5
      InstanceType: t2.micro