AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy a single EC2 instance with minimal configuration

Parameters:
  # Let's allow the user to choose what instance type upon deployment
  InstanceTypeParameter: 
    Type: String
    Default: t2.micro
    AllowedValues: 
      - t2.micro
      - t2.medium
      - m5.large
    Description: Enter t2.micro, m3.medium, or m5.large. Default is t2.micro.

Resources:

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-04681a1dbd79675a5
      InstanceType:
        Ref: InstanceTypeParameter  # Use the parameter specified
      SubnetId: subnet-64d3ac01 # Specify a subnet
      Tags:  # We'll give our instance some useful identifiers
        -
          Key: Name
          Value: My EC2 Instance
        -
          Key: Project
          Value: Workshop