AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy a single EC2 instance with minimal configuration

Mappings:

  # Specify different configs for different environments/regions
  EnvironmentMap:
    Dev:
      MinSize: 1
    Prod:
      MinSize: 2
  RegionMap:
    us-west-2:
      Ami: ami-6cd6f714
      Subnets:
        - subnet-24bc0f6f
        - subnet-24bc0f6f
    us-east-1:
      Ami: ami-04681a1dbd79675a5
      Subnets:
        - subnet-64d3ac01
        - subnet-91bcc3ca

Parameters:

  InstanceTypeParameter: 
    Type: String
    Default: t2.micro
    AllowedValues: 
      - t2.micro
      - m1.small
      - m1.large
    Description: Enter t2.micro, m1.small, or m1.large. Default is t2.micro.
  # Ask the user which environment we're deploying too
  Environment:
    Type: String
    Default: Dev
    AllowedValues:
      - Dev
      - Prod
    Description: Enter the environment that this is being deployed into.
    
Conditions:
  inProd:
    !Equals [!Ref Environment, 'Prod']

Resources:

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !FindInMap [RegionMap, !Ref 'AWS::Region', Ami]  # Lookup AMI from the mapping
      InstanceType:
        Ref: InstanceTypeParameter
      Monitoring: # Turn on monitoring if in Production
        !If [inProd, true, !Ref 'AWS::NoValue']
      Tags: 
        -
          Key: Name
          Value: My EC2 Instance
        -
          Key: Project
          Value: Workshop